global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: '$ALERTMANAGER_SMTP_FROM'
  smtp_auth_username: '$ALERTMANAGER_SMTP_USERNAME'
  smtp_auth_password: '$ALERTMANAGER_SMTP_PASSWORD'
  smtp_require_tls: true

route:
  group_by: ['alertname', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'email-receiver'
  routes:
    - match:
        severity: critical
      receiver: 'email-receiver'
      repeat_interval: 4h
    - match:
        severity: warning
      receiver: 'email-receiver'
      repeat_interval: 12h

receivers:
  - name: 'email-receiver'
    email_configs:
      - to: '$ALERTMANAGER_EMAIL_TO'
        send_resolved: true
        headers:
          Subject: '[{{ .Status | toUpper }}] {{ .GroupLabels.alertname }} - Rejuve Bio Monitoring'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']